// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cxesecxyrndveookvlzz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN4ZXNlY3h5cm5kdmVvb2t2bHp6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzQ4ODY1MDAsImV4cCI6MjA5MDQ2MjUwMH0.d_jY4pWyvRVqM8v6CSameL-UQ6yn52Cmxkf2vmUcivI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});